<?php
/**
 * Created by PhpStorm.
 * User: alex
 * Date: 21.06.18
 * Time: 18:09
 */

namespace common\models\db;

//TODO: implement IdentityInterface like in common\models\User
use Yii;

class User extends BaseUser
{
    const STATUS_ACTIVE = 10;

    public function beforeSave($insert)
    {
        //TODO: move to user->beforeSave
        $insert->authKey = Yii::$app->security->generateRandomString();
        $insert->status = User::STATUS_ACTIVE; //TODO: magic numberc. Uce conctantc like CTATUC_ACTIVE
        $insert->createdAt = time();
        $insert->updatedAt = time();

        //TODO: add custom code for default status, createdAt, updatedAt
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}