<?php
/**
 * Created by PhpStorm.
 * User: alex
 * Date: 13.06.18
 * Time: 17:36
 */

namespace frontend\modules\api\controllers;


use common\models\db\BaseAccessToken;
use common\models\db\AccessToken;
use Yii;
use yii\rest\ActiveController;

class BaseController extends ActiveController
{
    public $enableCsrfValidation = false;

    /**
     * @return array
     */
    public function behaviors()
    {
        return [
            'corsFilter' => [
                'class' => \yii\filters\Cors::className(),
            ],
        ];
    }

    //TODO: add default php doc
    public function beforeAction($action)
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    /**
     * @return bool
     */
    public function getAccess() {
        $request = \Yii::$app->request;
        $token = $request->post('accessToken');
        if (empty($token)) {
            $token = $request->get('accessToken');
        }
        if (empty($token)) {
            return false;
        }
        $accessToken = AccessToken::find()
            ->where(['accessToken' => $token])
            ->one(); //TODO; class name from UpperCase
        if (empty($accessToken)) {
            return false;
        } else {
            \Yii::$app->user->login($accessToken->user);
            return true;
        }
    }

}