<?php
/**
 * Created by PhpStorm.
 * User: alex
 * Date: 25.05.18
 * Time: 15:51
 */

//TODO: move to frontend/module.../api
namespace app\modules\api\controllers;

use common\models\db\accessToken;
use common\models\db\User;
use Yii;
use yii\rest\ActiveController;

class UserController extends ActiveController
{
    public $modelClass = 'app\models\User';
    public $enableCsrfValidation = false;


    public function behaviors()
    {
        return [
            'corsFilter' => [
                'class' => \yii\filters\Cors::className(),
            ],
        ];
    }

    public function beforeAction($action)
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }



    /**
     * @api {post} /api/user/login Авторизовать пользователя
     * @apiDescription Метод для авторизации существующих пользователей
     * @apiName login
     * @apiGroup user
     *
     * @apiParam {String} email E-mail
     * @apiParam {String} password Password
     *
     * @apiSuccess {String} accessTokken Токен доступа
     */
    public function actionLogin()
    {
        $request = Yii::$app->request;

        $email = $request->post('email');
        $password = $request->post('password');

        $user = User::findOne(['email' => $email]);
        if (!$user) {
            return ['error' => 'User not found'];
        }

        if (Yii::$app->getSecurity()->validatePassword($password, $user->passwordHash)) {
            // all good, logging user in
            $accessToken = AccessToken::find()->where(['userId' => $user->id])->one();
            return ['accessToken' => $accessToken->accessToken];
        } else {
            // wrong password
            return ['error' => 'Wrong password'];
        }
    }



    /**
     * @api {post} /api/user/register Зарегистрировать нового пользователя
     * @apiDescription Метод для регистрации новых пользователей
     * @apiName register
     * @apiGroup user
     *
     * @apiParam {String} login Login
     * @apiParam {String} email E-mail
     * @apiParam {String} password Password
     *
     * @apiSuccess {String} accessTokken Токен доступа
     */
    public function  actionRegister()
    {
        $request = Yii::$app->request;

        $login = $request->post('login');
        $email = $request->post('email');
        $password = $request->post('password');

        $model = User::find()->where(['username' => $login])->one();
        //TODO: update formatting
        if($model) {
            return ['error' => 'User already exists'];
        }

        //Create user
        $user = new User();
        $user->username = $login;
        $user->email = $email;
        $user->passwordHash = Yii::$app->security->generatePasswordHash($password);

        /*
        //TODO: move to user->beforeSave
        $user->authKey = Yii::$app->security->generateRandomString();
        $user->status = User::STATUS_ACTIVE; //TODO: magic numberc. Uce conctantc like CTATUC_ACTIVE
        $user->createdAt = time();
        $user->updatedAt = time();
        */
        $user->save();

        //Get token
        $accessToken = new AccessToken(); //TODO: class name from Upper case
        $accessToken->accessToken = Yii::$app->security->generateRandomString();
        $accessToken->userId = $user->id;
        $accessToken->save();

        return ['token' => $accessToken->accessToken];
    }

}